# This workflow builds and releases consol binaries for all platforms
# Triggers on git tags (e.g., v1.0.1)

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Run tests
        run: go test -v ./...

      - name: Build binaries
        run: |
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o consol-linux-amd64 .

          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o consol-linux-arm64 .

          # macOS Intel
          GOOS=darwin GOARCH=amd64 go build -o consol-darwin-amd64 .

          # macOS Apple Silicon
          GOOS=darwin GOARCH=arm64 go build -o consol-darwin-arm64 .

          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -o consol-windows-amd64.exe .

      - name: Generate checksums
        run: |
          sha256sum consol-* > checksums.txt

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            consol-linux-amd64 \
            consol-linux-arm64 \
            consol-darwin-amd64 \
            consol-darwin-arm64 \
            consol-windows-amd64.exe \
            checksums.txt \
            --notes "Git merge conflict resolution TUI tool. Download the binary for your platform below and follow installation instructions in the README."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

